import type { Metadata } from 'next';
import { Inter, Roboto, Noto_Sans_JP } from 'next/font/google';

import { JoyUIThemeProvider } from '@/components/JoyUIThemeProvider';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'], weight: '400' });
const notosansjp = Noto_Sans_JP({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={notosansjp.className}>
        <JoyUIThemeProvider>{children}</JoyUIThemeProvider>
      </body>
    </html>
  );
}
